require 'active_record'
require 'yaml'
require 'rake'
require "logger"

task :default => :migrate

desc "Migrate the database through scripts in db/migrate. Target specific version with VERSION=x"
task :migrate => :environment do
  ActiveRecord::Migrator.migrate('db/migrate', ENV["VERSION"] ? ENV["VERSION"].to_i : nil )
end

task :environment do
  @config = YAML.load_file(File.join(File.dirname(__FILE__), 'config/database.yml'))
  ActiveRecord::Base.establish_connection(@config["development"])
  ActiveRecord::Base.logger = Logger.new(File.open('./log/database.log', 'a'))
end
